---
name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install pypa build
        run: "python -m pip install build"
      - name: Build
        run: "uv build && ls -l dist"
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-dist
          path: dist
  upload:
    name: Upload to PyPI
    environment: release
    needs: [build]
    runs-on: ubuntu-24.04
    if: github.repository == 'acristoffers/ahio' && github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
